/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaRunCPM */

#ifndef _Included_JavaRunCPM
#define _Included_JavaRunCPM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaRunCPM
 * Method:    startCPM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaRunCPM_startCPM
  (JNIEnv *, jobject);

/*
 * Class:     JavaRunCPM
 * Method:    readRAM
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JavaRunCPM_readRAM
  (JNIEnv *, jobject, jint);

/*
 * Class:     JavaRunCPM
 * Method:    writeRAM
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaRunCPM_writeRAM
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
