/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaRunCPM */

#ifndef _Included_JavaRunCPM
#define _Included_JavaRunCPM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaRunCPM
 * Method:    startCPM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaRunCPM_startCPM
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
