/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class j80_vdu_ttyCRT */

#ifndef _Included_j80_vdu_ttyCRT
#define _Included_j80_vdu_ttyCRT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     j80_vdu_ttyCRT
 * Method:    ttyPutchar
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_j80_vdu_ttyCRT_ttyPutchar
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     j80_vdu_ttyCRT
 * Method:    ttySetCursorPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_j80_vdu_ttyCRT_ttySetCursorPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     j80_vdu_ttyCRT
 * Method:    ttySetCursor
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_j80_vdu_ttyCRT_ttySetCursor
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     j80_vdu_ttyCRT
 * Method:    ttyKbhit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_j80_vdu_ttyCRT_ttyKbhit
  (JNIEnv *, jobject);

/*
 * Class:     j80_vdu_ttyCRT
 * Method:    ttyGetch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_j80_vdu_ttyCRT_ttyGetch
  (JNIEnv *, jobject);

/*
 * Class:     j80_vdu_ttyCRT
 * Method:    ttyGetNumRow
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_j80_vdu_ttyCRT_ttyGetNumRow
  (JNIEnv *, jobject);

/*
 * Class:     j80_vdu_ttyCRT
 * Method:    ttyGetNumCol
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_j80_vdu_ttyCRT_ttyGetNumCol
  (JNIEnv *, jobject);

/*
 * Class:     j80_vdu_ttyCRT
 * Method:    ttyInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_j80_vdu_ttyCRT_ttyInit
  (JNIEnv *, jobject);

/*
 * Class:     j80_vdu_ttyCRT
 * Method:    ttyReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_j80_vdu_ttyCRT_ttyReset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
